server:
  port: ${PORT:8080}
spring:
  application:
    name: booking-receipts-ms
  config:
    import: optional:file:.env[.properties]
  kafka:
    bootstrap-servers: ${KAFKA_URL}
    consumer:
      group-id: receipts-ms
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
    producer:
      retries: 1
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    topics:
      BOOKING_CREATED_TOPIC: BOOKING_CREATED_TOPIC
      BOOKING_RECEIPT_GENERATED_TOPIC: BOOKING_RECEIPT_GENERATED_TOPIC

cloud:
  aws:
    s3:
      region: ${S3_BUCKET_REGION:sa-east-1}
      bucket:
        name: ${S3_BUCKET_NAME:filesystem}